export { default as BankInfoTab } from './BankInfo.vue'
export { default as BusinessInfoTab } from './BusinessRegisteredAddress.vue'
export { default as DepositCreditLimitTab } from './DepositCreditLimit.vue'
export { default as GSTVATTab } from './GSTVAT.vue'
export { default as PersonalInfoTab } from './PersonalInformation.vue'
export { default as UpdatesTab } from './UpdateHistory.vue'
