import { url } from '../../global/api'

export const api = {
  'salesListing': url.apiUrl + '/sales-list',
  'downlineValidation': url.apiUrl + '/member-tree-downline-verify',
  'classicCheck': url.apiUrl + '/classic-member-verify',
  'salesProductSearch': url.apiUrl + '/sales/search-product-kitting',
  'taxInvoiceSearch': url.apiUrl + '/invoice-list',
  'taxInvoiceDetail': url.apiUrl + '/invoice-details',
  'salesCancellationInvoiceDetailSearch': url.apiUrl + '/sales/sale-cancellation-invoice-details',
  'salesCancellationCreation': url.apiUrl + '/sales/sale-cancellation-create',
  'salesCancellationListingSearch': url.apiUrl + '/sales/sale-cancellation-list',
  'salesCancellationDetail': url.apiUrl + '/sales/sale-cancellation-details',
  'retrieveTaxInvoicePDF': url.apiUrl + '/invoice/downloadpdf',
  'retrieveCreditNotePDF': url.apiUrl + '/sales/creditnote/downloadpdf',
  'salesProductEligible': url.apiUrl + '/sales/sales-product-eligible',
  'sales': url.apiUrl + '/sales',
  'salesDetails': url.apiUrl + '/sales-details',
  'paymentModes': url.apiUrl + '/payments/sales',
  'makePayment': url.apiUrl + '/payments/payment-make',
  'productExchangeListingSearch': url.apiUrl + '/sales-exchange-list',
  'productExchangeCreation': url.apiUrl + '/sales-exchange',
  'productExchangeDetail': url.apiUrl + '/sales-exchange-details',
  'cancellationBatchProcessRefund': url.apiUrl + '/sales/sale-cancellation-batch-refund',
  'retriveExchangeBillPDF': url.apiUrl + '/sales-exchange/exchangenote/downloadpdf',
  'legacySalesCancellationCreation': url.apiUrl + '/sales/lagacy-sale-cancellation-create',
  'aeonPaymentList': url.apiUrl + '/payments/aeon-payment-list',
  'aeonBatchRelease': url.apiUrl + '/payments/aeon-payment-cooling-off-release',
  'eppPaymentList': url.apiUrl + '/payments/epp-payment-list',
  'dailySalesReport': url.apiUrl + '/sale-daily-report',
  'submitEppApproval': url.apiUrl + '/payments/update-epp-moto-approve-code',
  'submitAeonAgreementNumber': url.apiUrl + '/payments/update-aeon-agreement-number',
  'downloadPreOrderNote': url.apiUrl + '/download-preorder-note',
  'batchCancelPayment': url.apiUrl + '/payments/payment-batch-cancel',
  'convertEppMotoSales': url.apiUrl + '/payments/epp-moto-sale-convert',
  'downloadAmpInvoice': url.apiUrl + '/download-auto-maintenance-invoice',
  'enrollmentTypeByCountry': url.apiUrl + '/enrollment-types/'
}
